version: 2

models:
  - name: stg_characters
    columns:
      - name: char_id
        tests:
          - unique
          - not_null
      - name: char_name
        tests:
          - accepted_values:
              values: ["Mario", "Luigi"]
      - name: occupation_id
        tests:
          - relationships:
              to: ref('stg_occupations')
              field: occ_id

  - name: stg_events
    columns:
      - name: event_id
        tests:
          - unique
          - not_null

  - name: stg_occupations
    columns:
      - name: occ_id
        tests:
          - unique
          - not_null
      - name: occ_name
        tests:
          - accepted_values:
              values: ["plumber"]

  - name: stg_worlds
    columns:
      - name: world_id
        tests:
          - unique
          - not_null
      - name: world_name
        tests:
          - unique
          - not_null
      - name: world
        tests:
          - accepted_values:
              values: [
                "World 1", 
                "World 2", 
                "World 3", 
                "World 4",
                "World 5",
                "World 6",
                "World 7",
                "World 8",
                "World 9",
              ]

  - name: mario3
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
